name: github-action-secrets

on:
  workflow_dispatch:


jobs:
  secrets-fetching:
    runs-on: ubuntu-latest
    steps:
      - name  : Echo secrets
        run : | 
          echo "MY Secret value ${{ secrets.SECRET_KEY}}"
          echo "Not existing secret ${{ secrets.not_saved}}"

      - name: Secret as env variable
        run: echo "SECRET value $AZURE_CREDENTIALS"
        env:
            AZURE_CREDENTIALS: ${{ secrets.SECRET_KEY }} 
    